language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then composer require "apigen/apigen: 4.0.0"; fi
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then composer require "scrutinizer/ocular: 1.1.1"; fi

script:
  - vendor/bin/paratest -f tests/
  #- phpunit --debug --exclude-group slow --log-json output.json