language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install

script:
  # - composer test
  #- phpunit --debug --exclude-group slow --log-json output.json
  ./vendor/bin/paratest -f tests/

after_script:
  #- php utils/test-timers.php