language: php

env:
  global:
    secure: GyUQF+c9zWoT6yX2iC9k0aQtt0EH/5bZtzo+/s3bGTCWBynyIdhu56efBjwq/tqj2GoF3LchlTlql3sVt83Ixt4rTrTDsMmMjJH6Avy1pKZg3/Q99AVrwYtkq4GhGwE5NMsJEC47CRNVMBewVpsRmfqqPj69FwrNVEFMG3n9wAQ=

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then composer require apigen/apigen:4.0.0; fi
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then composer require scrutinizer/ocular:1.1.1; fi
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHPUNIT_FLAGS="--coverage-clover=coverage.clover"; else PHPUNIT_FLAGS="" && phpenv config-rm xdebug.ini; fi

script:
  - vendor/bin/paratest -f tests/ $PHPUNIT_FLAGS

after_success:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then sh .generate.sh; fi
