language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then composer require 'apigen/apigen: 4.0.0'; fi

script:
  - vendor/bin/paratest -f tests/